version: '3.8'

services:
  # Banco de Dados MySQL
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_wp
      MYSQL_PASSWORD: senha_segura_123
      MYSQL_ROOT_PASSWORD: senha_root_segura
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  # Aplicação Wordpress
  webserver:
    image: wordpress:latest
    container_name: webserver
    restart: always
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: user_wp
      WORDPRESS_DB_PASSWORD: senha_segura_123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - app_data:/var/www/html
    networks:
      - wp_network

  # Proxy reverso (Nginx) - Único ponto de acesso externo
  webproxy:
    image: luish083/nginx-personalizado:latest
    container_name: webproxy
    restart: always
    depends_on:
      - webserver
    ports:
      - "8080:80"
    networks:
      - wp_network

# Definição de volumes e redes
volumes:
  db_data:
  app_data:

networks:
  wp_network:
    driver: bridge
