---
- name: Provisionamento Debian com Docker e Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Atualizar o cache do apt e fazer upgrade do sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes dependentes para o Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Adicionar chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Adicionar repositório oficial do Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalar Docker e Docker Compose Plugin (v2)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: yes
        state: present

    - name: Garantir que o serviço do Docker está rodando
      service:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório da aplicação
      file:
        path: /opt/minha_aplicacao
        state: directory
        mode: '0755'

    - name: Copiar o arquivo docker-compose.yml para a VM
      copy:
        src: ../docker-compose.yml
        dest: /opt/minha_aplicacao/docker-compose.yml
        mode: '0644'
          



    - name: Executar o Docker Compose (Inicializar aplicação)
      command: docker compose up -d
      args:
        chdir: /opt/minha_aplicacao
